// test_mkl_util.hpp
//
// Scalar-type dispatch for the MKL-backed suites, so each suite is written once
// as a template and runs in FP64 and FP32:
//
//   cqr_mkl<T>  the routines under test,
//               cqr_mkl_?{geqrf,ormqr,potrf,sytrfnp,sytrsnp,sysvnp,trsm}_compact
//   mkl<T>      MKL's Compact API: sizes, pack/unpack, and MKL's own compact
//               kernels as references
//   lapack<T>   dense LAPACKE / CBLAS references
//
// Each is a struct of static forwarders specialized for double (d/D) and float
// (s/S); the specializations are generated by one macro per struct so the two
// cannot drift apart. Needs MKL headers; the MKL-free helpers (including
// compact<T>, the portable C API's dispatch) are in test_compact_util.hpp.
//
// Assisted-by: Claude:claude-opus-4.8

#ifndef TEST_MKL_UTIL_HPP
#define TEST_MKL_UTIL_HPP

#include <mkl.h>
#include <mkl_compact.h>

#include "cqr_mkl_ext.h"
#include "cqr_mkl_alloc.h"
#include "test_compact_util.hpp"

namespace cqr::test {

template <class T> struct cqr_mkl;
template <class T> struct mkl;
template <class T> struct lapack;

// clang-format off
// NOLINTBEGIN(bugprone-macro-parentheses): T is a type name, p a token to paste
#define CQR_TEST_MKL_DISPATCH(T, p, P)                                                     \
template <> struct cqr_mkl<T> {                                                            \
    static void geqrf(MKL_LAYOUT layout, MKL_INT m, MKL_INT n, T *ap, MKL_INT ldap,       \
                      T *taup, T *work, MKL_INT lwork, MKL_INT *info,                      \
                      MKL_COMPACT_PACK fmt, MKL_INT nm)                                    \
    { cqr_mkl_##p##geqrf_compact(layout, m, n, ap, ldap, taup, work, lwork, info, fmt, nm); } \
    static void ormqr(MKL_LAYOUT layout, char side, char trans, MKL_INT m, MKL_INT n,     \
                      MKL_INT k, const T *ap, MKL_INT ldap, const T *taup, T *cp,          \
                      MKL_INT ldcp, T *work, MKL_INT lwork, MKL_INT *info,                 \
                      MKL_COMPACT_PACK fmt, MKL_INT nm)                                    \
    { cqr_mkl_##p##ormqr_compact(layout, side, trans, m, n, k, ap, ldap, taup, cp, ldcp,   \
                                 work, lwork, info, fmt, nm); }                            \
    static void potrf(MKL_LAYOUT layout, MKL_UPLO uplo, MKL_INT n, T *ap, MKL_INT ldap,   \
                      MKL_INT *info, MKL_COMPACT_PACK fmt, MKL_INT nm)                     \
    { cqr_mkl_##p##potrf_compact(layout, uplo, n, ap, ldap, info, fmt, nm); }              \
    static void sytrfnp(MKL_LAYOUT layout, MKL_UPLO uplo, MKL_INT n, T *ap, MKL_INT ldap, \
                        MKL_INT *info, MKL_COMPACT_PACK fmt, MKL_INT nm)                   \
    { cqr_mkl_##p##sytrfnp_compact(layout, uplo, n, ap, ldap, info, fmt, nm); }            \
    static void sytrsnp(MKL_LAYOUT layout, MKL_UPLO uplo, MKL_INT n, MKL_INT nrhs,        \
                        const T *ap, MKL_INT ldap, T *bp, MKL_INT ldbp, MKL_INT *info,     \
                        MKL_COMPACT_PACK fmt, MKL_INT nm)                                  \
    { cqr_mkl_##p##sytrsnp_compact(layout, uplo, n, nrhs, ap, ldap, bp, ldbp, info, fmt,   \
                                   nm); }                                                  \
    static void sysvnp(MKL_LAYOUT layout, MKL_UPLO uplo, MKL_INT n, MKL_INT nrhs, T *ap,  \
                       MKL_INT ldap, T *bp, MKL_INT ldbp, MKL_INT *info,                   \
                       MKL_COMPACT_PACK fmt, MKL_INT nm)                                   \
    { cqr_mkl_##p##sysvnp_compact(layout, uplo, n, nrhs, ap, ldap, bp, ldbp, info, fmt,    \
                                  nm); }                                                   \
    static void trsm(MKL_LAYOUT layout, MKL_SIDE side, MKL_UPLO uplo, MKL_TRANSPOSE tr,   \
                     MKL_DIAG diag, MKL_INT m, MKL_INT n, T alpha, const T *ap,            \
                     MKL_INT ldap, T *bp, MKL_INT ldbp, MKL_COMPACT_PACK fmt, MKL_INT nm)  \
    { cqr_mkl_##p##trsm_compact(layout, side, uplo, tr, diag, m, n, alpha, ap, ldap, bp,   \
                                ldbp, fmt, nm); }                                          \
};                                                                                         \
template <> struct mkl<T> {                                                                \
    static int vlen(MKL_COMPACT_PACK fmt) { return cqr::detail::vlen_for_format<T>(fmt); } \
    static MKL_INT get_size(MKL_INT m, MKL_INT n, MKL_COMPACT_PACK fmt, MKL_INT nm)        \
    { return mkl_##p##get_size_compact(m, n, fmt, nm); }                                   \
    static void gepack(MKL_LAYOUT layout, MKL_INT m, MKL_INT n, const T *const *a,        \
                       MKL_INT lda, T *ap, MKL_INT ldap, MKL_COMPACT_PACK fmt, MKL_INT nm) \
    { mkl_##p##gepack_compact(layout, m, n, a, lda, ap, ldap, fmt, nm); }                  \
    static void geunpack(MKL_LAYOUT layout, MKL_INT m, MKL_INT n, T *const *a,            \
                         MKL_INT lda, const T *ap, MKL_INT ldap, MKL_COMPACT_PACK fmt,     \
                         MKL_INT nm)                                                       \
    { mkl_##p##geunpack_compact(layout, m, n, a, lda, ap, ldap, fmt, nm); }                \
    static void geqrf(MKL_LAYOUT layout, MKL_INT m, MKL_INT n, T *ap, MKL_INT ldap,       \
                      T *taup, T *work, MKL_INT lwork, MKL_INT *info,                      \
                      MKL_COMPACT_PACK fmt, MKL_INT nm)                                    \
    { mkl_##p##geqrf_compact(layout, m, n, ap, ldap, taup, work, lwork, info, fmt, nm); }  \
    static void potrf(MKL_LAYOUT layout, MKL_UPLO uplo, MKL_INT n, T *ap, MKL_INT ldap,   \
                      MKL_INT *info, MKL_COMPACT_PACK fmt, MKL_INT nm)                     \
    { mkl_##p##potrf_compact(layout, uplo, n, ap, ldap, info, fmt, nm); }                  \
    static void getrfnp(MKL_LAYOUT layout, MKL_INT m, MKL_INT n, T *ap, MKL_INT ldap,     \
                        MKL_INT *info, MKL_COMPACT_PACK fmt, MKL_INT nm)                   \
    { mkl_##p##getrfnp_compact(layout, m, n, ap, ldap, info, fmt, nm); }                   \
    static void trsm(MKL_LAYOUT layout, MKL_SIDE side, MKL_UPLO uplo, MKL_TRANSPOSE tr,   \
                     MKL_DIAG diag, MKL_INT m, MKL_INT n, T alpha, const T *ap,            \
                     MKL_INT ldap, T *bp, MKL_INT ldbp, MKL_COMPACT_PACK fmt, MKL_INT nm)  \
    { mkl_##p##trsm_compact(layout, side, uplo, tr, diag, m, n, alpha, ap, ldap, bp, ldbp, \
                            fmt, nm); }                                                    \
};                                                                                         \
template <> struct lapack<T> {                                                             \
    static lapack_int geqrf(int layout, lapack_int m, lapack_int n, T *a, lapack_int lda, \
                            T *tau)                                                        \
    { return LAPACKE_##p##geqrf(layout, m, n, a, lda, tau); }                              \
    static lapack_int orgqr(int layout, lapack_int m, lapack_int n, lapack_int k, T *a,   \
                            lapack_int lda, const T *tau)                                  \
    { return LAPACKE_##p##orgqr(layout, m, n, k, a, lda, tau); }                           \
    static lapack_int ormqr(int layout, char side, char trans, lapack_int m,              \
                            lapack_int n, lapack_int k, const T *a, lapack_int lda,        \
                            const T *tau, T *c, lapack_int ldc)                            \
    { return LAPACKE_##p##ormqr(layout, side, trans, m, n, k, a, lda, tau, c, ldc); }      \
    static lapack_int potrf(int layout, char uplo, lapack_int n, T *a, lapack_int lda)    \
    { return LAPACKE_##p##potrf(layout, uplo, n, a, lda); }                                \
    static void gemm(CBLAS_LAYOUT layout, CBLAS_TRANSPOSE ta, CBLAS_TRANSPOSE tb,         \
                     MKL_INT m, MKL_INT n, MKL_INT k, T alpha, const T *a, MKL_INT lda,    \
                     const T *b, MKL_INT ldb, T beta, T *c, MKL_INT ldc)                   \
    { cblas_##p##gemm(layout, ta, tb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc); }     \
};
// NOLINTEND(bugprone-macro-parentheses)
// clang-format on

CQR_TEST_MKL_DISPATCH(double, d, D)
CQR_TEST_MKL_DISPATCH(float, s, S)
#undef CQR_TEST_MKL_DISPATCH

// Absolute tolerance for the cross-checks against MKL's own compact kernels on
// the same packed input: the two implementations share the algorithm and sign
// convention but not the arithmetic order, so agreement is far inside the
// backward-error gates yet not bit-exact.
template <class T> double cross_tol();
template <> inline double cross_tol<double>()
{
    return 1e-9;
}
template <> inline double cross_tol<float>()
{
    return 1e-4;
}

} // namespace cqr::test

#endif // TEST_MKL_UTIL_HPP
